"""add billing_cycle field to subscription plan table

Revision ID: 73f8d217a936
Revises: 360c5da77fff
Create Date: 2026-06-19 19:10:09.034370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f8d217a936'
down_revision: Union[str, Sequence[str], None] = '360c5da77fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('billing_cycle', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'billing_cycle')
    # ### end Alembic commands ###
